version: "3.8"

services:
  mysql:
    image: mysql/mysql-server:8.0.30
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'work'
      MYSQL_USER: 'admin'             # change it !
      MYSQL_PASSWORD: 'admin'         # change it !
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 10
#    ports:
#      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./backend/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    networks: {net}

  backend:
    build:
      context: ./backend
    container_name: rabota-backend
    networks: {net}
    volumes:
      - ./backend/config.toml:/opt/config.toml:ro
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: rabota-frontend
    ports: ["80:80"]
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: {net}
    depends_on:
      - backend

networks: {net}
