[service]
    host        = "0.0.0.0"
    port        = 8081
    secret      = "-uuid-"      # change it !
    run_mode    = "release"

    [service.timeouts]
        write   = "5m"
        read    = "5m"
        idle    = "10m"

[db]
    host        = "mysql"
    port        = 3306
    user        = "admin"       # change it !
    password    = "admin"       # change it !
    dbname      = "work"
    timeout     = "10s"
    id_len      = 10
    id_tries    = 50
